# Generated by Django 6.1 on 2026-08-10 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'актёр',
                'verbose_name_plural': 'Актёры',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('genre', models.CharField(max_length=256, verbose_name='Жанр')),
                ('year', models.IntegerField(verbose_name='Год')),
            ],
            options={
                'verbose_name': 'фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Персонаж')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_list.actor', verbose_name='Актёр')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_list.movie', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'роль',
                'verbose_name_plural': 'Роли',
            },
        ),
    ]
