# Generated by Django 6.1 on 2026-08-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='portrait',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
    ]
