# Generated by Django 6.1 on 2026-08-10 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_list', '0002_actor_portrait_alter_movie_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='Character',
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name': 'персонаж', 'verbose_name_plural': 'Персонажи'},
        ),
    ]
