# Generated by Django 6.1 on 2026-08-12 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor_list', '0001_initial'),
        ('movie_list', '0003_rename_role_character_alter_character_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actor_list.actor', verbose_name='Актёр'),
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
    ]
