# Generated by Django 6.1 on 2026-08-12 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor_list', '0001_initial'),
        ('movie_list', '0004_alter_character_actor_delete_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='actor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='actor_list.actor', verbose_name='Актёр'),
        ),
    ]
