# Generated by Django 6.1 on 2026-09-06 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor_list', '0001_initial'),
        ('movie_list', '0005_alter_character_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='actor_list.actor', verbose_name='Актёр'),
        ),
    ]
