# Generated by Django 6.1 on 2026-09-06 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_list', '0006_alter_character_actor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name'], 'verbose_name': 'персонаж', 'verbose_name_plural': 'Персонажи'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title'], 'verbose_name': 'фильм', 'verbose_name_plural': 'Фильмы'},
        ),
    ]
