# Generated by Django 6.1 on 2026-08-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('date_of_birth', models.DateField(default='01.01.2000', verbose_name='Дата рождения')),
                ('bio', models.TextField(verbose_name='Биография')),
                ('portrait', models.ImageField(null=True, upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'актёр',
                'verbose_name_plural': 'Актёры',
            },
        ),
    ]
