# Generated by Django 6.1 on 2026-09-06 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actor_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['name'], 'verbose_name': 'актёр', 'verbose_name_plural': 'Актёры'},
        ),
    ]
